/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketsIndexRouteImport } from './routes/tickets/index'
import { Route as TicketsNewRouteImport } from './routes/tickets/new'
import { Route as DepartmentLoginRouteImport } from './routes/department/login'
import { Route as DepartmentLayoutRouteImport } from './routes/department/_layout'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as DepartmentLayoutIndexRouteImport } from './routes/department/_layout.index'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout.index'
import { Route as DepartmentLayoutTicketsRouteImport } from './routes/department/_layout.tickets'
import { Route as AdminLayoutTicketsRouteImport } from './routes/admin/_layout.tickets'
import { Route as AdminLayoutKnowledgeRouteImport } from './routes/admin/_layout.knowledge'
import { Route as AdminLayoutDepartmentsRouteImport } from './routes/admin/_layout.departments'
import { Route as ApiPublicHooksEscalateTicketsRouteImport } from './routes/api/public/hooks/escalate-tickets'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsNewRoute = TicketsNewRouteImport.update({
  id: '/tickets/new',
  path: '/tickets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentLoginRoute = DepartmentLoginRouteImport.update({
  id: '/department/login',
  path: '/department/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentLayoutRoute = DepartmentLayoutRouteImport.update({
  id: '/department/_layout',
  path: '/department',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentLayoutIndexRoute = DepartmentLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DepartmentLayoutRoute,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const DepartmentLayoutTicketsRoute = DepartmentLayoutTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => DepartmentLayoutRoute,
} as any)
const AdminLayoutTicketsRoute = AdminLayoutTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutKnowledgeRoute = AdminLayoutKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutDepartmentsRoute = AdminLayoutDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const ApiPublicHooksEscalateTicketsRoute =
  ApiPublicHooksEscalateTicketsRouteImport.update({
    id: '/api/public/hooks/escalate-tickets',
    path: '/api/public/hooks/escalate-tickets',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/department': typeof DepartmentLayoutRouteWithChildren
  '/department/login': typeof DepartmentLoginRoute
  '/tickets/new': typeof TicketsNewRoute
  '/tickets/': typeof TicketsIndexRoute
  '/admin/departments': typeof AdminLayoutDepartmentsRoute
  '/admin/knowledge': typeof AdminLayoutKnowledgeRoute
  '/admin/tickets': typeof AdminLayoutTicketsRoute
  '/department/tickets': typeof DepartmentLayoutTicketsRoute
  '/admin/': typeof AdminLayoutIndexRoute
  '/department/': typeof DepartmentLayoutIndexRoute
  '/api/public/hooks/escalate-tickets': typeof ApiPublicHooksEscalateTicketsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/login': typeof AdminLoginRoute
  '/department/login': typeof DepartmentLoginRoute
  '/tickets/new': typeof TicketsNewRoute
  '/tickets': typeof TicketsIndexRoute
  '/admin/departments': typeof AdminLayoutDepartmentsRoute
  '/admin/knowledge': typeof AdminLayoutKnowledgeRoute
  '/admin/tickets': typeof AdminLayoutTicketsRoute
  '/department/tickets': typeof DepartmentLayoutTicketsRoute
  '/admin': typeof AdminLayoutIndexRoute
  '/department': typeof DepartmentLayoutIndexRoute
  '/api/public/hooks/escalate-tickets': typeof ApiPublicHooksEscalateTicketsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/department/_layout': typeof DepartmentLayoutRouteWithChildren
  '/department/login': typeof DepartmentLoginRoute
  '/tickets/new': typeof TicketsNewRoute
  '/tickets/': typeof TicketsIndexRoute
  '/admin/_layout/departments': typeof AdminLayoutDepartmentsRoute
  '/admin/_layout/knowledge': typeof AdminLayoutKnowledgeRoute
  '/admin/_layout/tickets': typeof AdminLayoutTicketsRoute
  '/department/_layout/tickets': typeof DepartmentLayoutTicketsRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/department/_layout/': typeof DepartmentLayoutIndexRoute
  '/api/public/hooks/escalate-tickets': typeof ApiPublicHooksEscalateTicketsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/feedback'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin'
    | '/admin/login'
    | '/department'
    | '/department/login'
    | '/tickets/new'
    | '/tickets/'
    | '/admin/departments'
    | '/admin/knowledge'
    | '/admin/tickets'
    | '/department/tickets'
    | '/admin/'
    | '/department/'
    | '/api/public/hooks/escalate-tickets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/feedback'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin/login'
    | '/department/login'
    | '/tickets/new'
    | '/tickets'
    | '/admin/departments'
    | '/admin/knowledge'
    | '/admin/tickets'
    | '/department/tickets'
    | '/admin'
    | '/department'
    | '/api/public/hooks/escalate-tickets'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/feedback'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin/_layout'
    | '/admin/login'
    | '/department/_layout'
    | '/department/login'
    | '/tickets/new'
    | '/tickets/'
    | '/admin/_layout/departments'
    | '/admin/_layout/knowledge'
    | '/admin/_layout/tickets'
    | '/department/_layout/tickets'
    | '/admin/_layout/'
    | '/department/_layout/'
    | '/api/public/hooks/escalate-tickets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  FeedbackRoute: typeof FeedbackRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  DepartmentLayoutRoute: typeof DepartmentLayoutRouteWithChildren
  DepartmentLoginRoute: typeof DepartmentLoginRoute
  TicketsNewRoute: typeof TicketsNewRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
  ApiPublicHooksEscalateTicketsRoute: typeof ApiPublicHooksEscalateTicketsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/new': {
      id: '/tickets/new'
      path: '/tickets/new'
      fullPath: '/tickets/new'
      preLoaderRoute: typeof TicketsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/department/login': {
      id: '/department/login'
      path: '/department/login'
      fullPath: '/department/login'
      preLoaderRoute: typeof DepartmentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/department/_layout': {
      id: '/department/_layout'
      path: '/department'
      fullPath: '/department'
      preLoaderRoute: typeof DepartmentLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/department/_layout/': {
      id: '/department/_layout/'
      path: '/'
      fullPath: '/department/'
      preLoaderRoute: typeof DepartmentLayoutIndexRouteImport
      parentRoute: typeof DepartmentLayoutRoute
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/department/_layout/tickets': {
      id: '/department/_layout/tickets'
      path: '/tickets'
      fullPath: '/department/tickets'
      preLoaderRoute: typeof DepartmentLayoutTicketsRouteImport
      parentRoute: typeof DepartmentLayoutRoute
    }
    '/admin/_layout/tickets': {
      id: '/admin/_layout/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminLayoutTicketsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/knowledge': {
      id: '/admin/_layout/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AdminLayoutKnowledgeRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/departments': {
      id: '/admin/_layout/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminLayoutDepartmentsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/api/public/hooks/escalate-tickets': {
      id: '/api/public/hooks/escalate-tickets'
      path: '/api/public/hooks/escalate-tickets'
      fullPath: '/api/public/hooks/escalate-tickets'
      preLoaderRoute: typeof ApiPublicHooksEscalateTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutDepartmentsRoute: typeof AdminLayoutDepartmentsRoute
  AdminLayoutKnowledgeRoute: typeof AdminLayoutKnowledgeRoute
  AdminLayoutTicketsRoute: typeof AdminLayoutTicketsRoute
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutDepartmentsRoute: AdminLayoutDepartmentsRoute,
  AdminLayoutKnowledgeRoute: AdminLayoutKnowledgeRoute,
  AdminLayoutTicketsRoute: AdminLayoutTicketsRoute,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface DepartmentLayoutRouteChildren {
  DepartmentLayoutTicketsRoute: typeof DepartmentLayoutTicketsRoute
  DepartmentLayoutIndexRoute: typeof DepartmentLayoutIndexRoute
}

const DepartmentLayoutRouteChildren: DepartmentLayoutRouteChildren = {
  DepartmentLayoutTicketsRoute: DepartmentLayoutTicketsRoute,
  DepartmentLayoutIndexRoute: DepartmentLayoutIndexRoute,
}

const DepartmentLayoutRouteWithChildren =
  DepartmentLayoutRoute._addFileChildren(DepartmentLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  FeedbackRoute: FeedbackRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  DepartmentLayoutRoute: DepartmentLayoutRouteWithChildren,
  DepartmentLoginRoute: DepartmentLoginRoute,
  TicketsNewRoute: TicketsNewRoute,
  TicketsIndexRoute: TicketsIndexRoute,
  ApiPublicHooksEscalateTicketsRoute: ApiPublicHooksEscalateTicketsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
